#!/usr/bin/env node

var lib = require('allexlib'),
  BasicProgram = require('allex_basicprogramsdklib')(lib),
  Node = require('allex_nodehelpersserverruntimelib')(lib),
  Protoboard = require('allex_protoboardhelperssdklib')(lib),
  addpage = require('..')(lib).add;

var p = new BasicProgram(__dirname)

p.program
  .usage('[options] <pagename>')
  .option('-f, --force', 'Force add page');

p.go();
if (!p.program.args[0]){
  Node.error('Insufficient arguments');
  p.showHelp();
  process.exit();
}

addpage (p.program.args[0], {
  force : !!p.program.force,
  frameworks : p.program.frameworks
}).done (
  Node.info.bind(Node),
  Node.error.bind(Node)
);
